version: "3"
services:
  api:
    container_name: wgpy_api
    image: wgpy:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uvicorn", "wgpy.api.main:app", "--host", "0.0.0.0", "--port", "80"]
    env_file:
      - .env
    ports:
      - 127.0.0.1:8888:80
    depends_on:
      - worker

  worker:
    container_name: wgpy_worker
    image: wgpy:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "-m", "remoulade", "wgpy.worker"]
    env_file:
      - .env
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
